name: Builder le conteneur et le publier sur le registre GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configurer Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Se connecter au GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Builder le conteneur et le publier sur le registre GitHub Packages
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/ezpositoo/ue19-lab-05
