name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write  # Assure-toi que tu peux écrire dans le registre GitHub Container Registry

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}  # Utilise ton nom d'utilisateur GitHub
        password: ${{ secrets.GITHUB_TOKEN }}  # Utilise le jeton GitHub pour l'authentification

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/mvslm/ue19-lab-05:latest . 

    - name: Cache Trivy binary
      uses: actions/cache@v4
      with:
        path: ~/.cache/trivy
        key: ${{ runner.os }}-trivy-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-trivy-

    - name: Scan image for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/mvslm/ue19-lab-05:latest
        format: table
        severity: HIGH,CRITICAL

    - name: Push Docker image
      run: |
        docker push ghcr.io/mvslm/ue19-lab-05:latest  # Assure-toi que le nom du dépôt est correct
