name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write  # Assure-toi que tu peux écrire dans le registre GitHub Container Registry

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
      with:
        egress-policy: audit

    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}  # Utilise ton nom d'utilisateur GitHub
        password: ${{ secrets.GITHUB_TOKEN }}  # Utilise le jeton GitHub pour l'authentification

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/mvslm/ue19-lab-05:latest .  # Assure-toi que le tag correspond au nom du dépôt

    - name: Cache Trivy binary
      uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      with:
        path: ~/.cache/trivy
        key: ${{ runner.os }}-trivy-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-trivy-

    - name: Scan image for vulnerabilities
      uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 # master
      with:
        image-ref: ghcr.io/mvslm/ue19-lab-05:latest
        format: table
        severity: HIGH,CRITICAL

    - name: Push Docker image
      run: |
        docker push ghcr.io/mvslm/ue19-lab-05:latest  # Assure-toi que le nom du dépôt est correct
